/* Asumsi: ID pemain hanya ada 1 digit, pemain hanya ada dua, yaitu w dan v */
writeLocMap(Loc)    :-
    \+ property(Loc),
    write('      ').

writeLocMap(Loc)    :-
    property(Loc),
    \+ ownProp(_,Loc),
    write('      ').

writeLocMap(Loc)    :-
    property(Loc),
    ownProp(Player,Loc),
    levelProp(Loc,4),
    format('  ~wL  ', [Player]).

writeLocMap(Loc)    :-
    property(Loc),
    ownProp(Player,Loc),
    levelProp(Loc,Level),
    format('  ~w~w  ', [Player,Level]).

writePlayer(Loc)    :-
    \+ playerLocation(_,Loc),
    write('      ').

writePlayer(Loc)    :-
    \+ playerLocation(_,Loc),
    write('      ').

writePlayer(Loc)    :-
    playerLocation(w,Loc),
    playerLocation(v,Loc),
    write(' W  V '),
    !.

writePlayer(Loc)    :-
    playerLocation(w,Loc),
    format('   W  ', [_Player]).

writePlayer(Loc)    :-
    playerLocation(v,Loc),
    format('   V  ', [_Player]).

map :-
    write('=================  INI MAP  ================= '), nl,
    playerLocation(w,LocPlayer1),
    playerLocation(v,LocPlayer2),
    write('             '),
    writePlayer(fp),
    write(' '),
    writePlayer(e1),
    write(' '),
    writePlayer(e2),
    write(' '),
    writePlayer(e3),
    write(' '),
    writePlayer(cc01),
    write(' '),
    writePlayer(f1),
    write(' '),
    writePlayer(f2),
    write(' '),
    writePlayer(f3),
    write(' '),
    writePlayer(wt),
    nl,
    write('             '),
    writeLocMap(fp),
    write(' '),
    writeLocMap(e1),
    write(' '),
    writeLocMap(e2),
    write(' '),
    writeLocMap(e3),
    write(' '),
    writeLocMap(cc01),
    write(' '),
    writeLocMap(f1),
    write(' '),
    writeLocMap(f2),
    write(' '),
    writeLocMap(f3),
    write(' '),
    writeLocMap(wt),
    nl,
    write('            ----------------------------------------------------------------'),
    nl,
    write('            |  FP  |  E1  |  E2  |  E3  | CC01 |  F1  |  F2  |  F3  |  WT  |'),
    nl,
    writePlayer(d3),
    writeLocMap(d3),
    write('|  D3  |------------------------------------------------|  G1  |'),
    writeLocMap(g1),
    writePlayer(g1),
    nl,
    writePlayer(d2),
    writeLocMap(d2),
    write('|  D2  |                                                |  G2  |'),
    writeLocMap(g2),
    writePlayer(g2),
    nl,
    writePlayer(d1),
    writeLocMap(d1),
    write('|  D1  |                                                |  G3  |'),
    writeLocMap(g3),
    writePlayer(g3),
    nl,
    writePlayer(tx02),
    writeLocMap(tx02),
    write('| TX02 |                 M O N O P O L Y                | TX01 |'),
    writeLocMap(tx01),
    writePlayer(tx01),
    nl,
    writePlayer(cf),
    writeLocMap(cf),
    write('|  CF  |                                                | CC02 |'),
    writeLocMap(cc02),
    writePlayer(cc02),
    nl,
    writePlayer(c2),
    writeLocMap(c2),
    write('|  C2  |                                                |  H1  |'),
    writeLocMap(h1),
    writePlayer(h1),
    nl,
    writePlayer(c1),
    writeLocMap(c1),
    write('|  C1  |------------------------------------------------|  H2  |'),
    writeLocMap(h2),
    writePlayer(h2),
    nl,
    write('            |  JL  |  B3  |  B2  |  B1  | CC03 |  A3  |  A2  |  A1  |  GO  |'),
    nl,
    write('            ----------------------------------------------------------------'),
    nl,
    write('             '),
    writeLocMap(jl),
    write(' '),
    writeLocMap(b3),
    write(' '),
    writeLocMap(b2),
    write(' '),
    writeLocMap(b1),
    write(' '),
    writeLocMap(cc03),
    write(' '),
    writeLocMap(a3),
    write(' '),
    writeLocMap(a2),
    write(' '),
    writeLocMap(a1),
    write(' '),
    writeLocMap(go),
    nl,
    write('             '),
    writePlayer(jl),
    write(' '),
    writePlayer(b3),
    write(' '),
    writePlayer(b2),
    write(' '),
    writePlayer(b1),
    write(' '),
    writePlayer(cc03),
    write(' '),
    writePlayer(a3),
    write(' '),
    writePlayer(a2),
    write(' '),
    writePlayer(a1),
    write(' '),
    writePlayer(go),
    nl,
    nl,
    write('Posisi pemain:'),
    nl,
    format('W = ~w ~n',[LocPlayer1]),
    format('V = ~w ~n',[LocPlayer2]),
    !.