

/* Asumsi: ID pemain hanya ada 1 digit, pemain hanya ada dua, yaitu w dan v */
writeLocMap(Loc)    :-
    \+ property(Loc),
    write('    ').

writeLocMap(Loc)    :-
    property(Loc),
    \+ ownProp(_,Loc),
    write('    ').

writeLocMap(Loc)    :-
    property(Loc),
    ownProp(Player,Loc),
    levelProp(Loc,4),
    format(' ~wL', [Player]).

writeLocMap(Loc)    :-
    property(Loc),
    ownProp(Player,Loc),
    levelProp(Loc,Level),
    format(' ~w~w ', [Player,Level]).

map :- 
    playerLocation(player1,LocPlayer1),
    playerLocation(player2,LocPlayer2),
    write('     '),
    writeLocMap(fp),
    write(' '),
    writeLocMap(e1),
    write(' '),
    writeLocMap(e2),
    write(' '),
    writeLocMap(e3),
    write(' '),
    writeLocMap(cc1),
    write(' '),
    writeLocMap(f1),
    write(' '),
    writeLocMap(f2),
    write(' '),
    writeLocMap(f3),
    write(' '),
    writeLocMap(wt),
    nl,
    write('    ----------------------------------------------'),
    nl,
    write('    | FP | E1 | E2 | E3 | CC | F1 | F2 | F3 | WT |'),
    nl,
    writeLocMap(d3),
    write('| D3 |----------------------------------| G1 |'),
    writeLocMap(g1),
    nl,
    writeLocMap(d2),
    write('| D2 |                                  | G2 |'),
    writeLocMap(g2),
    nl,
    writeLocMap(d1),
    write('| D1 |                                  | G3 |'),
    writeLocMap(g3),
    nl,
    writeLocMap(tx2),
    write('| TX |          M O N O P O L Y         | TX |'),
    writeLocMap(tx1),
    nl,
    writeLocMap(c3),
    write('| C3 |                                  | CC |'),
    writeLocMap(cc2),
    nl,
    writeLocMap(c2),
    write('| C2 |                                  | H1 |'),
    writeLocMap(h1),
    nl,
    writeLocMap(c1),
    write('| C1 |----------------------------------| H2 |'),
    writeLocMap(h2),
    nl,
    write('    | JL | B3 | B2 | B1 | CC | A3 | A2 | A1 | GO |'),
    nl,
    write('    ----------------------------------------------'),
    nl,
    write('     '),
    writeLocMap(jl),
    write(' '),
    writeLocMap(b3),
    write(' '),
    writeLocMap(b2),
    write(' '),
    writeLocMap(b1),
    write(' '),
    writeLocMap(cc3),
    write(' '),
    writeLocMap(a3),
    write(' '),
    writeLocMap(a2),
    write(' '),
    writeLocMap(a1),
    write(' '),
    writeLocMap(go),
    nl,
    nl,
    write('Posisi pemain:'),
    nl,
    format('W = ~w ~n',[LocPlayer1]),
    format('V = ~w',[LocPlayer2]),
    !.